spring:
  application:
    name: account-service
  config:
    import: optional:configserver:http://localhost:8888

       
#spring:
#  application:
#    name: account-service
#  datasource:
#    username: newroot
#    password: root
#    url: jdbc:mysql://localhost:3306/accountdb
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 5
#      auto-commit: true
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#server:
#  port: 0
#  error:
#    include-message: always
#eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
#  client:
#      serviceUrl:
#        defaultZone: http://localhost:8761/eureka
#customProperty:
#  test: PavanKumar
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh, health



#eureka.instance.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#customProperty:
#  test: Pavan
#management:
#  endpoints:
#    web:
#      exposure:
#        include: refresh
#  endpoint:
#    health:
#      show-details: always
#      group:
#        custom:
#          show-components: always

#management.endpoint.health.group.custom.show-components=always
#management.endpoint.health.group.custom.show-details=always


#url shdn't be hardcored
#shd be embeddable from the external source -> property and from property we have to use it
#Docker -> Properties(yml) -> Application(user,password and other urls)